### ISSUE TITLE
Executable conflict when install gem

### ISSUE THREAD

**Issue by diligasi** [fnando/cpf_cnpj#14]
Tryed to install your gem using `bundle install cpf_cnpj` and received the following message: `cpf_cnpj's executable "cnpj" conflicts with cpf_faker`, anny glue to solve it without overriding cpf_faker?

**Comment by fnando** [comment]
I know it's been a long time since you asked this, but here it goes:

You can install either gem binaries to a different directory. 

`gem install cpf_faker --bindir /tmp`

If you need to use those binaries, then use a different directory and add it to `$PATH`.
