### ISSUE TITLE
Still working with Ruby 2.6.3?

### ISSUE THREAD

**Issue by haroldofurtado** [fnando/cpf_cnpj#15]
Let me know if is still working, I couldn't use it with ActiveRecord (using validators).

**Comment by fnando** [comment]
I know it's been a long time since you asked, I'm sorry for that.

Yeah, looks like it's working just fine. I added ruby `2.6` and `2.7` to travis' testing matrix, and they're passing.

If you happen to have this error ever again, please post the backtrace.
