### ISSUE TITLE
Valid CPF returning nil in validation

### ISSUE THREAD

**Issue by JhoMartins** [fnando/cpf_cnpj#16]
This is a valid cpf number `01234567890` but when I call the `CPF.valid?` function I have this behavior: 
![Screen Shot 2019-10-25 at 11 50 13](https://user-images.githubusercontent.com/20273062/67581011-a3755a00-f71d-11e9-9fdc-4ddbce1437f0.png)

**Comment by fnando** [comment]
Sorry for taking forever to answer this. Yeah, that's fine. `nil` is a falsy value, and you shouldn't have any issues with it, unless you're type checking.

If you really need a boolean, use `!!CPF.valid?(number, strict: true)` to coerce the returning value.
