### ISSUE TITLE
Is there any possibility to split the cpf/cnpj into separate repositories and provide them as UMD?

### ISSUE THREAD

**Issue by fernandofleury** [fnando/cpf_cnpj#2]
I've been using CPF only for a while, and copied into a AMD wrapper in order to use with my requirejs project.
 
I was wondering why are both provided together. Since most of the times I was using CPF into my projects, It would be CPF only.

**Comment by fnando** [comment]
Because I think it makes sense. Code is small and I hate having super-mega-small modules like the NPM culture promotes. `cnpj.js` weights 1.8K uncompressed. It makes no sense splitting this.

**Comment by fernandofleury** [comment]
Okay. thanks for the heads up!
