### ISSUE TITLE
Migration to Github Actions made some tests failed

### ISSUE THREAD

**Issue by pedrofurtado** [fnando/cpf_cnpj#21]
@fnando After merge of https://github.com/fnando/cpf_cnpj/pull/18 , some tests failed. But I think it is not related to CI itself, but in source code.

I will investigate to get some clue 👍 🔍

**Comment by pedrofurtado** [comment]
The tests that failed are all about CLI, maybe we need to change something in Github action workflow to get it work well

**Comment by pedrofurtado** [comment]
There is a really strange behavior, @fnando :

If I run the tests locally in PC that is all green. But if I run the exactly same way in container, appears errors about mismatch of exit codes 🤔

**Comment by pedrofurtado** [comment]
Even in PC, sometimes the `bundle exec rake` run green, sometimes red. There is some randomness that may be causing this errors too

**Comment by pedrofurtado** [comment]
@fnando Have you any idea about the reason of this random failures? 🤔  I am able to help, in what you need 🤝

**Comment by fnando** [comment]
Fixed via fe9e15a2d2e3b546fddc50536f5c31a42e94c2e2
