### ISSUE TITLE
Valid CNPJ returning nil

### ISSUE THREAD

**Issue by enaoki** [fnando/cpf_cnpj#30]
Using version `0.5.0`

![image](https://user-images.githubusercontent.com/8048700/154094376-4e9d9318-7cc4-46e7-a7ac-c7f4abb07406.png)

![image](https://user-images.githubusercontent.com/8048700/154094641-ecbda915-a116-4959-ac74-507eb9ac89c5.png)

**Comment by LucasCarrias** [comment]
Hello @enaoki,

I think you called the wrong class.

```rb
CPF.valid?('21.062.813/0001-86'')
=> nil
```

```rb
CNPJ.valid?('21.062.813/0001-86')
=> true
```

**Comment by enaoki** [comment]
This's what you get when you don't read the docs properly...🤦‍♂️

My bad! Thanks!
