### ISSUE TITLE
Not generate unique when use generate

### ISSUE THREAD

**Issue by alencarandre** [fnando/cpf_cnpj#9]
In my model, I create unique index for CPF/CNPJ, and when I use CPF/CNPJ.generate in RSpec, not generate unique CPF/CPNJ and give validation error in Factory.

**Comment by fnando** [comment]
Are you generating the number inside a block? Something like `cpf { CPF.generate } `. Otherwise, you'll get the same document on every instance.

**Comment by alencarandre** [comment]
No. I'm gonna do that.

Thanks
